blockchain-certificates/cert-verifier-js

- README.md
- lib/verifier.js
- verifier.js
Add another tx api for fallback in case one is unavailable
> multiple tx apis for fallback

- lib/status.js
- lib/verifier.js
- verifier.js
PR for issue #2 . verify.js was generated by running `npm run build` but seeing the large diff from the file I am not sure whether I did it the correct way. Currently there's no test here, I can verify that the valid cert will fail if I add `"expires" : "<some date in the past>"` but I don't know how to correctly generate a new certificate JSON. Should I issue it using the cert-issuer? Copy-pasting the valid certificate and adding `expires` field makes the hash comparison fails.
Thanks for making blockcerts!
> Add expiry date checking

- config/default.js
- lib/bitcoinConnectors.js
- lib/checks.js
- lib/promisifiedRequests.js
- lib/verifier.js
- lib/verifierModels.js
- verifier.js
Make it easier for web component to deal with known vs unknown errors through VerifierError class
> improved error handling

- lib/checks.js
- lib/promisifiedRequests.js
- lib/verifier.js
- package-lock.json
- verifier.js
Followup from https://github.com/blockchain-certificates/cert-issuer/issues/64.
This was assuming certificates would not already contain a `@vocab` definition. The issue above describes why this change is safe (still ensures certificate has not been tampered with).
> allow certificates to use @vocab

- README.md
- lib/bitcoinExplorers.js
- lib/certificate.js
- lib/checks.js
- lib/ethereumExplorers.js
- lib/promisifiedRequests.js
- lib/utils.js
- lib/verifier.js
- package-lock.json
- package.json
- rollup.config.js
- tests/testCertificate.js
- tests/testVerifier.js
- tests/utils/readFile.js
- verifier-es.js
- verifier.js
enable working with Polymer 3 environment.
@raiseandfall could you check that the `verifier.js` code still works with the current places where we use it (or point me to them), as it has been generated by `rollup`. If so we can remove browserify.
> Expose Verifier as ES module

- package-lock.json
- package.json
- rollup-es5.config.js
- rollup.config.js
- verifier-iife.js
also the `es2015` preset in favor of `env`. I still would like to do one manual test on IE10 (standalone test project) before merging @raiseandfall.
> Remove browserify

- verifier-es.js
- verifier-iife.js
- verifier.js
> chore(build): build

- package-lock.json
updating vulnerable dependencies.
> chore(Packages): update packages

- CHANGELOG.md
This is purely a doc changes PR to prepare 2.0.1 release.
> doc(changelog): prepare for 2.0.1

- .npmrc
- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
Adding semantic-release to automate future package releases
> chore(NPM): add semantic-release

- README.md
- doc: updated broken links on README
- doc: added semantic release badge
> doc(README): updated broken links; added SR badge

- package-lock.json
> fix(Packages): fix vulnerabilities

- src/data/i18n.json
- test/application/domain/i18n/useCases/getSupportedLanguages.test.js
superseding: https://github.com/blockchain-certificates/cert-verifier-js/pull/116
> feat(I18n): add italian translations

- src/data/i18n.json
- test/application/domain/i18n/useCases/getSupportedLanguages.test.js
Adding Japanese language support.
I made a few changes so I've created a new pull request.
> feat(i18n): add Japanese translations

- src/data/i18n.json
Update for Fix/i18n final step https://github.com/blockchain-certificates/cert-verifier-js/pull/157
> Updated Italian language translations

- commitlint.config.js
- package-lock.json
- package.json
using fix rather than chore to trigger build with italian translations
> fix(Commits): ensure commits follow semantic-release convention

- README.md
> doc(README): fix API `signatureImage` wrong type

- src/certificate.js
- src/constants/certificateVersions.js
- src/parser.js
- test/application/certificate/certificate-v3.test.js
- test/fixtures/blockcerts-3.0-alpha.json
merging to v3 feature branch and not master to avoid early release.
> feat(Certificate): add ability to detect v3

- src/explorers/bitcoin/apis/bitpay.js
- src/explorers/bitcoin/apis/blockcypher.js
- src/explorers/bitcoin/apis/blockexplorer.js
- src/explorers/bitcoin/apis/blockstream.js
- src/explorers/bitcoin/bitcoin-explorer.js
- test/application/explorers/bitcoin/apis/bitpay.test.js
- test/application/explorers/bitcoin/apis/blockcypher.test.js
- test/application/explorers/bitcoin/apis/blockexplorer.test.js
- test/application/explorers/bitcoin/apis/blockstream.test.js
- renamed bitcoin explorer API parsing functions
> Refactor: rename parsing functions

- package-lock.json
- package.json
- src/explorers/explorer.ts
- src/helpers/object.ts
- test/e2e/explorerAPIs.test.ts
added testing around that execution to avoid future breakage
> [#846] Fix/parsing function

- src/domain/verifier/useCases/getIssuerProfile.ts
- src/parsers/parseV3.ts
- src/verifier.ts
The idea is to extract those steps to get a bit more automated control for the verification process. 
Other refactors in that area might come.
> Refactor verifier to isolate steps

- .travis.yml
error occurring on CI build with readable-stream, investigating
> chore(CI): debug Transform error (build 251881827)

- package-lock.json
- package.json
- test/e2e/verifier/mocknet-v3-valid.test.ts
Provide a general description of the code changes in your pull request... were there any bugs you had fixed? If so, mention them. If these bugs have open GitHub issues, be sure to tag them here as well, to keep the conversation linked together.
If there's anything else that's important and relevant to your pull request, mention that information here. This could include benchmarks, or other information.
If you are updating any of the CHANGELOG files or are asked to update the CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Thanks for contributing!
> fix(Mocknet): use latest version of jsonld-signatures-merkleproof2019

- package-lock.json
- package.json
- src/constants/contexts/EcdsaSecp256k1Signature2019Context.json
- src/constants/contexts/contexts-list.ts
- src/constants/contexts/did.v1.context.json
- src/constants/contexts/preloadedContexts.ts
- test/assertions/hyland-issuer-profile-secp256k1.json
- test/fixtures/issuer-blockcerts.json
Issuer profiles binding verificationMethod similar to a DID document need to add the DID context as the first entry of their `@context` property.
> feat(Deps): bump jsonld-signatures

- package.json
Remove node-fetch deletion in postinstall
> chore(npm): remove postinstall instruction

- package.json
- test/manual-testing/fixtures/fixtures.mjs
- test/manual-testing/node/request.mjs
fixing manual test command after update
No CI affected will merge directly
> test(node): fix manual test after node-fetch update

- package-lock.json
- package.json
Provide a general description of the code changes in your pull request... were there any bugs you had fixed? If so, mention them. If these bugs have open GitHub issues, be sure to tag them here as well, to keep the conversation linked together.
If there's anything else that's important and relevant to your pull request, mention that information here. This could include benchmarks, or other information.
If you are updating any of the CHANGELOG files or are asked to update the CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Thanks for contributing!
> chore(Release): revert semantic release to node 18 support

- README.md
Please review and merge @lemoustachiste @raiseandfall
> update w3c compliance test suite status
